### ISSUE TITLE
PRJ3 bug

### ISSUE THREAD

**Issue by SealSoul117** [Corle-hyz/ucas_cod_2020#1]
I noticed that you had a problem with the "queen" example in microbench. And I think this is caused by your alu.v. Check your code for "nor" caculation. It should be \~(A | B) instead of A~^B.

**Comment by Corle-hyz** [comment]
You are right, the "A ~^ B" I wrote should mean "XNOR" instead of "NOR". Thanks very much for pointing it out, I will correct it right now.
